/**
 * GENERATED by ui/scripts/gen-api.mjs from ../pleroma/serve/api-schema.json — DO NOT EDIT.
 * Regenerate: `npm run gen:api`. Freshness: `npm run check:api`.
 */

/** sha256 of the canonical schema JSON this client was generated from;
 *  compared with /info.api.schema_sha256 on connect. */
export const SCHEMA_SHA256 = "39ae827d698dcc0642c06f4675b7ca692d51e12cfc66710863da8740d30ee4ec";
/** the API major version this client speaks (/info.api.version). */
export const API_VERSION = "1";
/** the path prefix every generated route starts with. */
export const API_PREFIX = "/api/v1";
