/**
 * GENERATED by ui/scripts/gen-api.mjs from ../pleroma/serve/api-schema.json — DO NOT EDIT.
 * Regenerate: `npm run gen:api`. Freshness: `npm run check:api`.
 */

export interface paths {
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * what this server is: map, prompt mode, rulers, policies, dose band, API version
         * @description Legacy alias (same-origin, un-prefixed): `GET /info`.
         */
        get: operations["getInfo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * one session's histories, wear, current fan and probe
         * @description Legacy alias (same-origin, un-prefixed): `GET /state`. v1 NEVER creates the session: an unknown session is 404 `no_session`. The legacy alias creates it.
         */
        get: operations["getState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * every session, on disk and in memory
         * @description Legacy alias (same-origin, un-prefixed): `GET /sessions`.
         */
        get: operations["getSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * a running /loom or /probe's stage and harvest
         * @description Legacy alias (same-origin, un-prefixed): `GET /loom/progress`. v1 never creates the session (an unknown one reads `progress: null`); the legacy alias creates it.
         */
        get: operations["getLoomProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pool": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * harvest worker health, probed on request (2 s cache)
         * @description Legacy alias (same-origin, un-prefixed): `GET /pool`.
         */
        get: operations["getPool"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/atlas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * the atlas report (dead path, kept for a decision)
         * @deprecated
         * @description Legacy alias (same-origin, un-prefixed): `GET /atlas`.
         */
        get: operations["getAtlas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** this document: the OpenAPI 3.1 description of /api/v1 */
        get: operations["getSchema"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * say a turn on a branch (worn on `loom`)
         * @description Legacy alias (same-origin, un-prefixed): `POST /chat`. Mutating: a session snapshot is written after success.
         */
        post: operations["postChat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/loom": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * draw K futures of a contemplated turn; score, optionally probe and auto-wear
         * @description Legacy alias (same-origin, un-prefixed): `POST /loom`. Mutating: a session snapshot is written after success.
         */
        post: operations["postLoom"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/probe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * score the current fan with the probe gauge (optionally wear the pick)
         * @description Legacy alias (same-origin, un-prefixed): `POST /probe`. Mutating: a session snapshot is written after success.
         */
        post: operations["postProbe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * wear a candidate of the current fan
         * @description Legacy alias (same-origin, un-prefixed): `POST /wear`. Mutating: a session snapshot is written after success.
         */
        post: operations["postWear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/wear_code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * wear a lever from no draw (dead path, kept for a decision)
         * @deprecated
         * @description Legacy alias (same-origin, un-prefixed): `POST /wear_code`. Mutating: a session snapshot is written after success.
         */
        post: operations["postWearCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/undo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * pop the last exchange (returned, not discarded)
         * @description Legacy alias (same-origin, un-prefixed): `POST /undo`. Mutating: a session snapshot is written after success.
         */
        post: operations["postUndo"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * redraw the last reply under the current wear
         * @description Legacy alias (same-origin, un-prefixed): `POST /reroll`. Mutating: a session snapshot is written after success.
         */
        post: operations["postReroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * replace the last user turn and regenerate
         * @description Legacy alias (same-origin, un-prefixed): `POST /edit`. Mutating: a session snapshot is written after success.
         */
        post: operations["postEdit"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/truncate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * cut a branch back to its first keep_turns exchanges
         * @description Legacy alias (same-origin, un-prefixed): `POST /truncate`. Mutating: a session snapshot is written after success.
         */
        post: operations["postTruncate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unwear": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * take the wear off
         * @description Legacy alias (same-origin, un-prefixed): `POST /unwear`. Mutating: a session snapshot is written after success.
         */
        post: operations["postUnwear"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * forget the session entirely (the snapshot records the cleared session)
         * @description Legacy alias (same-origin, un-prefixed): `POST /reset`. Mutating: a session snapshot is written after success.
         */
        post: operations["postReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * reload one session from its snapshot
         * @description Legacy alias (same-origin, un-prefixed): `POST /restore`.
         */
        post: operations["postRestore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ApiInfo
         * @description ``/info.api`` — which API this server speaks (docs/API.md).
         */
        ApiInfo: {
            /**
             * Version
             * @constant
             */
            version: "1";
            /** Prefix */
            prefix: string;
            /**
             * Schema Sha256
             * @description sha256 of GET /api/v1/schema's canonical JSON
             */
            schema_sha256: string;
            /**
             * Auth Required
             * @description /api/v1 routes need a bearer token
             */
            auth_required: boolean;
            /**
             * Legacy Aliases Open
             * @description the un-prefixed aliases answer without a token
             */
            legacy_aliases_open: boolean;
        };
        /** AutoSelected */
        AutoSelected: {
            /** Policy */
            policy: string;
            /** Effective Policy */
            effective_policy: string;
            /** Index */
            index: number;
            /** Alpha */
            alpha: number;
            scores: components["schemas"]["FutureScores"];
            dose: components["schemas"]["DoseReceipt"];
            /** Lever Kind */
            lever_kind: string;
            effective_alpha: components["schemas"]["EffectiveAlpha"];
        };
        /**
         * AutoSpec
         * @description /loom's ``auto`` object: pick a candidate by ``policy`` and wear it.
         *
         *     ``from_mapping`` performs the do_loom coercions in their original order;
         *     ``lever_kind``/``dose_policy`` stay raw here and are resolved (and refused,
         *     with their codes) by ``resolve_lever_kind``/``resolve_dose_policy`` exactly
         *     where they always were — after ``pick_auto``.
         */
        AutoSpec: {
            /**
             * Policy
             * @description one of ['distinct', 'loudest', 'stay', 'swerve', 'gauge']; refused (400) otherwise
             * @enum {string}
             */
            policy: "distinct" | "loudest" | "stay" | "swerve" | "gauge";
            /**
             * Alpha
             * @description the dose the pick is worn at
             * @default 0.35
             */
            alpha?: number;
            /**
             * Lever Kind
             * @description absent -> --wear-lever-default
             * @default null
             */
            lever_kind?: ("absolute" | "contrast") | null;
            /**
             * Dose Policy
             * @description absent -> --dose-policy-default
             * @default null
             */
            dose_policy?: ("flat" | "predicted") | null;
        };
        /**
         * BranchBody
         * @description POST /undo and /reroll.
         */
        BranchBody: {
            /**
             * Session
             * @description the session tag; required on every POST
             */
            session: string;
            /**
             * Branch
             * @default loom
             * @enum {string}
             */
            branch?: "base" | "loom";
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatBody
         * @description POST /chat and /edit.
         */
        ChatBody: {
            /**
             * Session
             * @description the session tag; required on every POST
             */
            session: string;
            /**
             * Branch
             * @default loom
             * @enum {string}
             */
            branch?: "base" | "loom";
            /**
             * Text
             * @default
             */
            text?: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ChatResponse
         * @description POST /chat. ``dream``/``tail_kind`` lead the body in modelc mode.
         */
        ChatResponse: {
            /**
             * Dream
             * @default null
             */
            dream?: string | null;
            /**
             * Tail Kind
             * @default null
             */
            tail_kind?: string | null;
            /** Session */
            session: string;
            /** Branch */
            branch: string;
            /** Reply */
            reply: string;
            /** N Turns */
            n_turns: number;
            /** Dropped Messages */
            dropped_messages: number;
            worn: components["schemas"]["WornPublic"] | null;
            /** Elapsed S */
            elapsed_s: number;
        };
        /**
         * DoseBandInfo
         * @description ``dose_band_info_json`` — ``tier: "none"`` means UNCALIBRATED.
         */
        DoseBandInfo: {
            /** Tier */
            tier: string;
            /** Alpha Max */
            alpha_max: number | null;
            /** Source */
            source: string | null;
            /** Measured At */
            measured_at: string | null;
            /**
             * Notes
             * @description OPEN: the band file's own notes
             */
            notes: unknown;
            /** Map Fingerprint */
            map_fingerprint: string | null;
            /**
             * Derivation
             * @description OPEN: pleroma.dose.band derivation record
             */
            derivation: {
                [key: string]: unknown;
            } | null;
            /**
             * Zones
             * @description OPEN: DoseZone.to_json rows
             */
            zones: {
                [key: string]: unknown;
            }[] | null;
            /** Lever Quality Caveat */
            lever_quality_caveat: string | null;
        };
        /**
         * DoseReceipt
         * @description ``DoseScale.to_json()`` — the dose one wear applied, and why.
         */
        DoseReceipt: {
            /** Policy */
            policy: string;
            /** Scale */
            scale: number[];
            /** Scale Raw */
            scale_raw: number[];
            /** Scale Mean */
            scale_mean: number;
            /** Fan Mean Raw Norms */
            fan_mean_raw_norms: number[] | null;
            /** Candidate Raw Norms */
            candidate_raw_norms: number[] | null;
            /**
             * Clamped
             * @description one record per clamped site (open: pleroma.dose.policy)
             */
            clamped: {
                [key: string]: unknown;
            }[];
            /** Clamp Range */
            clamp_range: number[];
            /** Note */
            note: string;
        };
        /**
         * EditResponse
         * @description POST /edit: a /chat body plus what it replaced.
         */
        EditResponse: {
            /**
             * Dream
             * @default null
             */
            dream?: string | null;
            /**
             * Tail Kind
             * @default null
             */
            tail_kind?: string | null;
            /** Session */
            session: string;
            /** Branch */
            branch: string;
            /** Reply */
            reply: string;
            /** N Turns */
            n_turns: number;
            /** Dropped Messages */
            dropped_messages: number;
            worn: components["schemas"]["WornPublic"] | null;
            /** Elapsed S */
            elapsed_s: number;
            /** Replaced User */
            replaced_user: string;
            /** Replaced Assistant */
            replaced_assistant: string;
        };
        /**
         * EffectiveAlpha
         * @description ``effective_alpha_json`` — what alpha means once the dose scale is in.
         */
        EffectiveAlpha: {
            /** Alpha */
            alpha: number;
            /** Alpha Effective Mean */
            alpha_effective_mean: number;
            /** Alpha Effective Per Site */
            alpha_effective_per_site: number[];
            /** Alpha Effective Range */
            alpha_effective_range: number[];
            /** Note */
            note: string;
        };
        /**
         * ErrorBody
         * @description Every non-2xx JSON body the loom API sends.
         */
        ErrorBody: {
            /**
             * Error
             * @description the refusal, written for the operator; shown verbatim
             */
            error: string;
            /** @description stable machine-readable code (docs/API.md) */
            code: components["schemas"]["ErrorCode"];
        };
        /**
         * ErrorCode
         * @description Every ``code`` the loom API can put in an error body.
         *
         *     Additive only (docs/API.md "Versioning"): a code, once published, keeps
         *     its meaning for the life of ``/api/v1``.
         * @enum {string}
         */
        ErrorCode: "bad_request" | "not_found" | "session_required" | "no_session" | "unknown_branch" | "stale_loom" | "no_candidates" | "gauge_needs_probe" | "lever_kind_invalid" | "lever_kind_unavailable" | "dose_policy_invalid" | "dose_policy_unavailable" | "probe_prefix_mismatch" | "no_snapshot" | "unauthorized" | "forbidden_origin" | "internal";
        /**
         * Future
         * @description One future of a fan (``futures[i]`` on /loom, /probe, /state, /restore).
         */
        Future: {
            /** Index */
            index: number;
            /** N Tokens */
            n_tokens: number;
            /** Text */
            text: string;
            /** Harvested */
            harvested: boolean;
            /** Note */
            note: string | null;
            scores: components["schemas"]["FutureScores"];
            /** Code */
            code: number[] | null;
            /**
             * Code Contrast
             * @description absent on futures persisted without a contrast code
             * @default null
             */
            code_contrast?: number[] | null;
            /**
             * Dream
             * @default null
             */
            dream?: string | null;
            /**
             * Tail Kind
             * @default null
             */
            tail_kind?: string | null;
            /**
             * Modelc Dream Blocks
             * @default null
             */
            modelc_dream_blocks?: number | null;
            /**
             * Reply Words
             * @default null
             */
            reply_words?: number | null;
        };
        /**
         * FutureScores
         * @description Advisory per-future scores; each is present only when computable.
         */
        FutureScores: {
            /**
             * Distinct
             * @default null
             */
            distinct?: number | null;
            /**
             * Loudness
             * @default null
             */
            loudness?: number | null;
            /**
             * Predicted Dose Scale
             * @default null
             */
            predicted_dose_scale?: number | null;
            /**
             * Predicted Dose Scale Contrast
             * @default null
             */
            predicted_dose_scale_contrast?: number | null;
            /**
             * Cos To Worn
             * @default null
             */
            cos_to_worn?: number | null;
            /**
             * Gauge
             * @description probe-derived; null = unscorable
             * @default null
             */
            gauge?: number | null;
        };
        /**
         * GaugeCandidate
         * @description ``CandidateGauge.to_json()``.
         */
        GaugeCandidate: {
            /** Index */
            index: number;
            /** Gauge */
            gauge: number | null;
            /** Gauge Base Nr */
            gauge_base_nr: number | null;
            /** Gauge Steered Nr */
            gauge_steered_nr: number | null;
            /** Gauge Reps */
            gauge_reps: number;
            /** Note */
            note: string | null;
        };
        /** HistoryMessage */
        HistoryMessage: {
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system";
            /** Content */
            content: string;
            /**
             * Dream
             * @description modelc assistant turns only
             * @default null
             */
            dream?: string | null;
            /**
             * Tail Kind
             * @description modelc assistant turns only
             * @default null
             */
            tail_kind?: string | null;
        };
        /** InfoPersistence */
        InfoPersistence: {
            /** Enabled */
            enabled: boolean;
            /** Dir */
            dir: string;
            /** Writes */
            writes: number;
            /** Write Failures */
            write_failures: number;
            /** Restored Sessions */
            restored_sessions: number;
            /** Failed Sessions */
            failed_sessions: number;
            /** Last Error */
            last_error: string | null;
            /** Restore On Start */
            restore_on_start: boolean;
            /** Restore Errors */
            restore_errors: string[];
            /** Schema */
            schema: number;
        };
        /** InfoResponse */
        InfoResponse: {
            /** Map */
            map: string;
            /**
             * Map Meta
             * @description OPEN: whatever the map file carries
             */
            map_meta: {
                [key: string]: unknown;
            };
            /** Sites */
            sites: number[];
            /** Branches */
            branches: string[];
            /** Default K */
            default_k: number;
            /** Future Tokens */
            future_tokens: number;
            /** Detach Wear Default */
            detach_wear_default: boolean;
            /** N Sessions */
            n_sessions: number;
            /** Prompt Mode */
            prompt_mode: string;
            prompt_mode_detail: components["schemas"]["PromptModeDetail"] | null;
            /** Harvest Worker */
            harvest_worker: string | null;
            /** Harvest Workers */
            harvest_workers: string[] | null;
            /** Harvest Pool Width */
            harvest_pool_width: number;
            /** Restored Sessions */
            restored_sessions: number;
            persistence: components["schemas"]["InfoPersistence"];
            /** Auto Policies */
            auto_policies: components["schemas"]["TableRow"][];
            /** Loudness Ref */
            loudness_ref: number;
            dose_band: components["schemas"]["DoseBandInfo"];
            ruler: components["schemas"]["Ruler"];
            /** Auto Policies Unavailable */
            auto_policies_unavailable: components["schemas"]["TableRow"][];
            /** Auto Policy Caveat */
            auto_policy_caveat: string;
            probe: components["schemas"]["ProbeInfo"];
            /** Dose Policies */
            dose_policies: components["schemas"]["TableRow"][];
            /** Dose Policy Default */
            dose_policy_default: string;
            /** Dose Scale Clamp */
            dose_scale_clamp: number[];
            /** Lever Kinds */
            lever_kinds: components["schemas"]["TableRow"][];
            /** Lever Kind Default */
            lever_kind_default: string;
            api: components["schemas"]["ApiInfo"];
        };
        /** LoomBody */
        LoomBody: {
            /**
             * Session
             * @description the session tag; required on every POST
             */
            session: string;
            /**
             * Text
             * @description the contemplated next user turn (not committed)
             */
            text: string;
            /**
             * K
             * @description absent -> --default-k
             * @default null
             */
            k?: number | null;
            /**
             * Horizon
             * @description absent -> --future-tokens
             * @default null
             */
            horizon?: number | null;
            /**
             * @description pick and wear a candidate
             * @default null
             */
            auto?: components["schemas"]["AutoSpec"] | null;
            /**
             * Detach Wear
             * @description absent -> --detach-wear-default
             * @default null
             */
            detach_wear?: boolean | null;
            /**
             * Probe
             * @description absent/false: no probe; true: defaults; object: settings
             * @default null
             */
            probe?: boolean | components["schemas"]["ProbeSpec"] | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * LoomProgress
         * @description A live /loom or /probe's ``{stage, done, total}`` (+ harvest detail).
         */
        LoomProgress: {
            /** Stage */
            stage: string;
            /** Done */
            done: number;
            /** Total */
            total: number;
            /** @default null */
            gens?: components["schemas"]["ProgressGens"] | null;
            /**
             * Origin
             * @description probe harvest: gen id -> [candidate|null, rep]
             * @default null
             */
            origin?: (number | null)[][] | null;
        };
        /** LoomResponse */
        LoomResponse: {
            /** Session */
            session: string;
            /** Loom Id */
            loom_id: string;
            /** N Futures */
            n_futures: number;
            /** Horizon */
            horizon: number;
            /** Prompt Mode */
            prompt_mode: string;
            /** Prompt Length */
            prompt_length: number;
            /** Bins Prompt Floor */
            bins_prompt_floor: number;
            /** Bins Feasible */
            bins_feasible: boolean;
            /** Detach Wear */
            detach_wear: boolean;
            drawn_under_wear: components["schemas"]["WornIndexAlpha"] | null;
            /** Futures */
            futures: components["schemas"]["Future"][];
            spread: components["schemas"]["Spread"] | null;
            /** Fan Mean Raw Norms */
            fan_mean_raw_norms: number[] | null;
            /** Fan Mean Raw Norms Contrast */
            fan_mean_raw_norms_contrast: number[] | null;
            /** Contrast Note */
            contrast_note: string | null;
            auto_selected: components["schemas"]["AutoSelected"] | null;
            /** Probe */
            probe: components["schemas"]["ProbeReceipt"] | components["schemas"]["ProbeFailure"] | null;
            worn: components["schemas"]["WornPublic"] | null;
            timing_s: components["schemas"]["LoomTiming"];
            /** Harvest Via */
            harvest_via: string;
            /**
             * Harvest Worker Detail
             * @description OPEN: the harvest worker's own reply, or null
             */
            harvest_worker_detail: {
                [key: string]: unknown;
            } | null;
            /** Loom Dir */
            loom_dir: string;
        };
        /** LoomTiming */
        LoomTiming: {
            /** Generate */
            generate: number;
            /** Harvest */
            harvest: number;
        };
        /**
         * OpenObject
         * @description An object with no fixed shape (the dead /atlas report; the schema itself).
         */
        OpenObject: {
            [key: string]: unknown;
        };
        /** PoolResponse */
        PoolResponse: {
            /** Configured */
            configured: number;
            /** Alive */
            alive: number;
            /** Workers */
            workers: components["schemas"]["WorkerHealth"][];
            /** Timeout S */
            timeout_s: number;
            /** Probed At */
            probed_at: number;
            /** Pool Width Configured */
            pool_width_configured: number;
            /** Single Worker */
            single_worker: string | null;
        };
        /** PoppedTurn */
        PoppedTurn: {
            /** User */
            user: string;
            /** Assistant */
            assistant: string;
        };
        /**
         * ProbeBody
         * @description POST /probe: the whole body is the probe's settings, plus the prefix.
         */
        ProbeBody: {
            /**
             * Alpha
             * @description dose of each candidate's contrastive code
             * @default 0.35
             */
            alpha?: number;
            /**
             * Reps
             * @description replies per candidate; >=2 for `resolution`
             * @default 2
             */
            reps?: number;
            /**
             * Horizon
             * @description tokens per probe reply
             * @default 64
             */
            horizon?: number;
            /**
             * Base
             * @description 'fan' (leave-one-out) or 'fresh' (unworn replies)
             * @default fan
             * @enum {string}
             */
            base?: "fan" | "fresh";
            /**
             * N Base
             * @description unworn replies when base='fresh'
             * @default 3
             */
            n_base?: number;
            /**
             * @description /probe only: wear the pick with these settings
             * @default null
             */
            wear?: components["schemas"]["ProbeWearSpec"] | null;
            /** Session */
            session: string;
            /**
             * Text
             * @description the SAME contemplated turn the fan was drawn against
             */
            text: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * ProbeFailure
         * @description /loom's ``probe`` when the in-/loom probe failed; the draw survives.
         */
        ProbeFailure: {
            /** Error */
            error: string;
            /** Note */
            note: string;
        };
        /** ProbeInfo */
        ProbeInfo: {
            /** Available */
            available: boolean;
            /** Endpoint */
            endpoint: string;
            /** Policy Key */
            policy_key: string;
            /** Base Modes */
            base_modes: string[];
            /** Default Base */
            default_base: string;
            /** Default Reps */
            default_reps: number;
            /**
             * Cost Estimate
             * @description OPEN: loom_probe.estimate_cost_s, or {unavailable, why, note}
             */
            cost_estimate: {
                [key: string]: unknown;
            };
            /** Definition */
            definition: string;
            /** Label */
            label: string;
        };
        /**
         * ProbeReceipt
         * @description The probe receipt (``run_probe``; ``worn``/``wall_s`` added by /probe).
         */
        ProbeReceipt: {
            /** Loom Id */
            loom_id: string | null;
            /** K */
            k: number;
            /** Reps */
            reps: number;
            /** Alpha */
            alpha: number;
            /** Horizon */
            horizon: number;
            /** Base */
            base: string;
            /** N Base */
            n_base: number;
            /** N Spans Harvested */
            n_spans_harvested: number;
            /** Candidates */
            candidates: components["schemas"]["GaugeCandidate"][];
            /** Ranking */
            ranking: number[];
            /** Pick */
            pick: number | null;
            /** Dead Rows */
            dead_rows: string[];
            /** Session Worn During Draw */
            session_worn_during_draw: boolean;
            /** Clean Regime */
            clean_regime: boolean;
            /**
             * Resolution
             * @description OPEN: loom_probe.resolution_report's variance decomposition
             */
            resolution: {
                [key: string]: unknown;
            };
            timing_s: components["schemas"]["ProbeTiming"];
            /** Harvest Via */
            harvest_via: string;
            /**
             * Harvest Worker Detail
             * @description OPEN: the harvest worker's own reply, or null
             */
            harvest_worker_detail: {
                [key: string]: unknown;
            } | null;
            /** Probe Dir */
            probe_dir: string;
            /** Absolute Comparable */
            absolute_comparable: boolean;
            /** Label */
            label: string;
            /**
             * @description /probe with `wear` only
             * @default null
             */
            worn?: components["schemas"]["WornPublic"] | null;
            /**
             * Wall S
             * @description /probe only
             * @default null
             */
            wall_s?: number | null;
        };
        /** ProbeResponse */
        ProbeResponse: {
            /** Session */
            session: string;
            probe: components["schemas"]["ProbeReceipt"];
            /** Futures */
            futures: components["schemas"]["Future"][];
            worn: components["schemas"]["WornPublic"] | null;
        };
        /**
         * ProbeSpec
         * @description The probe's settings: /loom's ``probe`` object, or /probe's whole body.
         *
         *     ``from_mapping`` performs run_probe's coercions in their original order
         *     (alpha, reps, horizon, base, n_base); the range checks stay in run_probe.
         *     ``wear`` is read (and type-checked) by do_probe, after the probe ran — it
         *     is only meaningful on /probe.
         */
        ProbeSpec: {
            /**
             * Alpha
             * @description dose of each candidate's contrastive code
             * @default 0.35
             */
            alpha?: number;
            /**
             * Reps
             * @description replies per candidate; >=2 for `resolution`
             * @default 2
             */
            reps?: number;
            /**
             * Horizon
             * @description tokens per probe reply
             * @default 64
             */
            horizon?: number;
            /**
             * Base
             * @description 'fan' (leave-one-out) or 'fresh' (unworn replies)
             * @default fan
             * @enum {string}
             */
            base?: "fan" | "fresh";
            /**
             * N Base
             * @description unworn replies when base='fresh'
             * @default 3
             */
            n_base?: number;
            /**
             * @description /probe only: wear the pick with these settings
             * @default null
             */
            wear?: components["schemas"]["ProbeWearSpec"] | null;
        };
        /** ProbeTiming */
        ProbeTiming: {
            /** Generate */
            generate: number;
            /** Harvest */
            harvest: number;
            /** Total */
            total: number;
        };
        /**
         * ProbeWearSpec
         * @description /probe's optional ``wear``: wear the probe's pick when it has one.
         */
        ProbeWearSpec: {
            /**
             * Alpha
             * @description absent -> the probe's alpha
             * @default null
             */
            alpha?: number | null;
            /**
             * Dose Policy
             * @default null
             */
            dose_policy?: ("flat" | "predicted") | null;
            /**
             * Lever Kind
             * @default null
             */
            lever_kind?: ("absolute" | "contrast") | null;
        };
        /** ProgressGens */
        ProgressGens: {
            /** N Gens */
            n_gens: number;
            /** Harvested */
            harvested: number[];
        };
        /** ProgressResponse */
        ProgressResponse: {
            /** Session */
            session: string;
            progress: components["schemas"]["LoomProgress"] | null;
        };
        /** PromptModeDetail */
        PromptModeDetail: {
            /** Temperature */
            temperature: number;
            /** Top P */
            top_p: number;
            /** Stop Strings */
            stop_strings: string[] | null;
            /** Chat Template Present */
            chat_template_present: boolean;
            /**
             * Modelc Header Name
             * @default null
             */
            modelc_header_name?: string | null;
            /**
             * Modelc Header
             * @default null
             */
            modelc_header?: string | null;
            /**
             * Modelc Header Is Bare
             * @default null
             */
            modelc_header_is_bare?: boolean | null;
            /**
             * Raw Turn Join
             * @default null
             */
            raw_turn_join?: string | null;
            /**
             * Raw History Note
             * @default null
             */
            raw_history_note?: string | null;
        };
        /** RerollResponse */
        RerollResponse: {
            /**
             * Dream
             * @default null
             */
            dream?: string | null;
            /**
             * Tail Kind
             * @default null
             */
            tail_kind?: string | null;
            /** Session */
            session: string;
            /** Branch */
            branch: string;
            /** Reply */
            reply: string;
            /** Replaced */
            replaced: string;
            /** Reroll N */
            reroll_n: number;
            /** N Turns */
            n_turns: number;
            /** Dropped Messages */
            dropped_messages: number;
            worn: components["schemas"]["WornPublic"] | null;
            /** Elapsed S */
            elapsed_s: number;
        };
        /** ResetResponse */
        ResetResponse: {
            /** Session */
            session: string;
            /**
             * Cleared
             * @constant
             */
            cleared: true;
            /** Worn */
            worn: null;
        };
        /** RestoreResponse */
        RestoreResponse: {
            /** Session */
            session: string;
            /**
             * Restored
             * @constant
             */
            restored: true;
            /** File */
            file: string;
            /** N Turns */
            n_turns: {
                [key: string]: number;
            };
            /** N Looms */
            n_looms: number;
            /** Loom Id */
            loom_id: string | null;
            worn: components["schemas"]["WornPublic"] | null;
            /** Futures */
            futures: components["schemas"]["Future"][];
        };
        /** Ruler */
        Ruler: {
            /** Norm Ref In Force */
            norm_ref_in_force: number[] | null;
            /** Norm Ref In Force Mean */
            norm_ref_in_force_mean: number | null;
            /** Which */
            which: string | null;
            /** Alternatives */
            alternatives: {
                [key: string]: components["schemas"]["RulerAlternative"];
            };
            /** Note */
            note: string;
        };
        /** RulerAlternative */
        RulerAlternative: {
            /** Norm Ref */
            norm_ref: number[];
            /** Mean */
            mean: number;
            /** In Force */
            in_force: boolean;
        };
        /**
         * SessionBody
         * @description POST /unwear, /reset, /restore.
         */
        SessionBody: {
            /**
             * Session
             * @description the session tag; required on every POST
             */
            session: string;
        } & {
            [key: string]: unknown;
        };
        /**
         * SessionRow
         * @description ``SessionListing.to_json()``.
         */
        SessionRow: {
            /** Session */
            session: string;
            /** File */
            file: string;
            /** Ok */
            ok: boolean;
            /** In Memory */
            in_memory: boolean;
            /** N Turns */
            n_turns: {
                [key: string]: number;
            };
            /** N Messages */
            n_messages: number;
            /** N Looms */
            n_looms: number;
            /** Loom Id */
            loom_id: string | null;
            /**
             * Worn
             * @description in-memory rows: the live wear; on-disk rows: the persisted record
             */
            worn: components["schemas"]["WornPublic"] | components["schemas"]["WornRecord"] | null;
            /** Modified Unix */
            modified_unix: number;
            /** Modified Iso */
            modified_iso: string;
            /** Size Bytes */
            size_bytes: number;
            /** Error */
            error: string | null;
        };
        /** SessionsResponse */
        SessionsResponse: {
            /** Sessions */
            sessions: components["schemas"]["SessionRow"][];
            /** N Sessions */
            n_sessions: number;
            persistence: components["schemas"]["StoreInfo"];
        };
        /** Spread */
        Spread: {
            /** Mean Pairwise Distance */
            mean_pairwise_distance: number;
            /** N Scored */
            n_scored: number;
            /** Loudness Ref */
            loudness_ref: number;
        };
        /** StateResponse */
        StateResponse: {
            /** Session */
            session: string;
            /** Histories */
            histories: {
                [key: string]: components["schemas"]["HistoryMessage"][];
            };
            worn: components["schemas"]["WornPublic"] | null;
            /** Loom Id */
            loom_id: string | null;
            /** Futures */
            futures: components["schemas"]["Future"][];
            /** N Looms */
            n_looms: number;
            loom_in_progress: components["schemas"]["LoomProgress"] | null;
            probe: components["schemas"]["ProbeReceipt"] | null;
            /** Probe Note */
            probe_note: string | null;
        };
        /**
         * StoreInfo
         * @description ``SessionStore.to_json()``.
         */
        StoreInfo: {
            /** Enabled */
            enabled: boolean;
            /** Dir */
            dir: string;
            /** Writes */
            writes: number;
            /** Write Failures */
            write_failures: number;
            /** Restored Sessions */
            restored_sessions: number;
            /** Failed Sessions */
            failed_sessions: number;
            /** Last Error */
            last_error: string | null;
        };
        /**
         * TableRow
         * @description A row of a copy table (/info's policies, kinds, dose policies): the
         *     ``key`` is the contract; the other fields are prose that grows.
         */
        TableRow: {
            /** Key */
            key: string;
        } & {
            [key: string]: unknown;
        };
        /** TruncateBody */
        TruncateBody: {
            /**
             * Session
             * @description the session tag; required on every POST
             */
            session: string;
            /**
             * Branch
             * @default loom
             * @enum {string}
             */
            branch?: "base" | "loom";
            /** Keep Turns */
            keep_turns: number;
        } & {
            [key: string]: unknown;
        };
        /** TruncateResponse */
        TruncateResponse: {
            /** Session */
            session: string;
            /** Branch */
            branch: string;
            /** N Turns */
            n_turns: number;
            /** Dropped Messages */
            dropped_messages: number;
        };
        /** UndoResponse */
        UndoResponse: {
            /** Session */
            session: string;
            /** Branch */
            branch: string;
            popped: components["schemas"]["PoppedTurn"];
            /** N Turns */
            n_turns: number;
        };
        /** UnwearResponse */
        UnwearResponse: {
            /** Session */
            session: string;
            /** Worn */
            worn: null;
        };
        /** WearBody */
        WearBody: {
            /**
             * Session
             * @description the session tag; required on every POST
             */
            session: string;
            /** Index */
            index: number;
            /**
             * Alpha
             * @default 0.5
             */
            alpha?: number;
            /**
             * Loom Id
             * @description the draw this wear belongs to; a stale id is refused (stale_loom)
             * @default null
             */
            loom_id?: string | null;
            /**
             * Dose Policy
             * @default null
             */
            dose_policy?: ("flat" | "predicted") | null;
            /**
             * Lever Kind
             * @default null
             */
            lever_kind?: ("absolute" | "contrast") | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * WearCodeBody
         * @description POST /wear_code: wear a code from another conversation (no UI calls it; the API keeps it).
         */
        WearCodeBody: {
            /**
             * Session
             * @description the session tag; required on every POST
             */
            session: string;
            /**
             * Alpha
             * @default 0.35
             */
            alpha?: number;
            /**
             * Group
             * @default null
             */
            group?: string | null;
            /**
             * Axis
             * @default null
             */
            axis?: number | null;
            /**
             * Pole
             * @default null
             */
            pole?: ("low" | "high") | null;
            /**
             * Rank
             * @default 0
             */
            rank?: number;
            /**
             * Random Seed
             * @default null
             */
            random_seed?: number | null;
            /**
             * Code
             * @default null
             */
            code?: number[] | null;
            /**
             * Code Kind
             * @default absolute
             * @enum {string}
             */
            code_kind?: "absolute" | "differential";
            /**
             * Dose Policy
             * @default null
             */
            dose_policy?: "flat" | null;
        } & {
            [key: string]: unknown;
        };
        /** WearCodeResponse */
        WearCodeResponse: {
            /** Session */
            session: string;
            worn: components["schemas"]["WornPublic"];
            /** Sites */
            sites: number[];
            /**
             * Source
             * @description OPEN (dead path): explicit_code | random_direction | bank_group
             */
            source: {
                [key: string]: unknown;
            };
        };
        /** WearResponse */
        WearResponse: {
            /** Session */
            session: string;
            worn: components["schemas"]["WornPublic"];
            /** Sites */
            sites: number[];
            dose: components["schemas"]["DoseReceipt"];
            effective_alpha: components["schemas"]["EffectiveAlpha"];
            /** Lever Kind */
            lever_kind: string;
        };
        /** WorkerHealth */
        WorkerHealth: {
            /** Url */
            url: string;
            /**
             * State
             * @enum {string}
             */
            state: "ok" | "busy" | "down" | "error";
            /** Latency Ms */
            latency_ms: number | null;
            /** Detail */
            detail: string | null;
        };
        /**
         * WornIndexAlpha
         * @description /loom's ``drawn_under_wear``: what was ATTACHED for this draw.
         */
        WornIndexAlpha: {
            /** Index */
            index: number;
            /** Alpha */
            alpha: number;
            /** Loom Id */
            loom_id: string | null;
        };
        /**
         * WornPublic
         * @description ``LoomSession.worn_public()`` — the session's wear, minus the vectors.
         */
        WornPublic: {
            /**
             * Index
             * @description candidate index; -1 for a /wear_code wear
             */
            index: number;
            /** Alpha */
            alpha: number;
            /** Loom Id */
            loom_id: string | null;
            /** Per Site Norms At Alpha1 */
            per_site_norms_at_alpha1: number[];
            /** Code */
            code: number[] | null;
            /**
             * Active
             * @description false: restored metadata, nothing attached
             */
            active: boolean;
            dose: components["schemas"]["DoseReceipt"] | null;
            /** Lever Kind */
            lever_kind: string | null;
        };
        /**
         * WornRecord
         * @description ``WornSnapshot.to_json()`` — a wear as persisted (GET /sessions, on-disk rows).
         */
        WornRecord: {
            /** Index */
            index: number;
            /** Alpha */
            alpha: number;
            /** Loom Id */
            loom_id: string | null;
            /** Code */
            code: number[] | null;
            /** Per Site Norms At Alpha1 */
            per_site_norms_at_alpha1: number[];
            /** Loom Dir */
            loom_dir: string | null;
            /** Map Fingerprint */
            map_fingerprint: string | null;
            /** Source */
            source: string | null;
            /**
             * Dose
             * @description the persisted dose receipt, as stored
             */
            dose: {
                [key: string]: unknown;
            } | null;
            /** Lever Kind */
            lever_kind: string | null;
            /** Contrast Peers */
            contrast_peers: number[] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getInfo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InfoResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getState: {
        parameters: {
            query: {
                /** @description the session tag */
                session: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StateResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionsResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getLoomProgress: {
        parameters: {
            query?: {
                /** @description the session tag; empty reads nothing */
                session?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getPool: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PoolResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getAtlas: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenObject"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    getSchema: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OpenObject"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postChat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postLoom: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoomBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoomResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postProbe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProbeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postWear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WearBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WearResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postWearCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WearCodeBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WearCodeResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postUndo: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UndoResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postReroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BranchBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RerollResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postEdit: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postTruncate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TruncateBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TruncateResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postUnwear: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnwearResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResetResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    postRestore: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionBody"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RestoreResponse"];
                };
            };
            /** @description error — `code` is machine-readable */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
