// Generate the typed API surface from the COMMITTED OpenAPI document.
//
//   node scripts/gen-api.mjs           write src/api/schema.d.ts + src/api/schema-meta.ts
//   node scripts/gen-api.mjs --check   exit 1 if either file is stale (writes nothing)
//
// The source of truth is ../pleroma/serve/api-schema.json (itself kept fresh by
// tests/unit/serve/test_api.py::test_committed_schema_is_fresh). This script is
// the only writer of the two generated files; never edit them by hand.
//
// schema-meta.ts carries SCHEMA_SHA256: the sha256 of the schema's canonical
// JSON exactly as the server computes it for /info.api.schema_sha256
// (pleroma/serve/schema.py: json.dumps(schema, sort_keys=True,
// separators=(",", ":"), ensure_ascii=False), UTF-8). The client compares the
// two on connect, so a server built from a different contract is reported, not
// discovered. tests/unit/test_ui_frontend.py asserts the two hashes agree.
import { createHash } from "node:crypto";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(fileURLToPath(import.meta.url));
const uiRoot = resolve(here, "..");
const schemaPath = resolve(uiRoot, "..", "pleroma", "serve", "api-schema.json");
const outTypes = resolve(uiRoot, "src", "api", "schema.d.ts");
const outMeta = resolve(uiRoot, "src", "api", "schema-meta.ts");
const check = process.argv.includes("--check");

/** Python's json.dumps(x, sort_keys=True, separators=(",", ":"), ensure_ascii=False). */
export function pythonCanonicalJson(value) {
  const enc = (v) => {
    if (v === null) return "null";
    if (typeof v === "boolean") return v ? "true" : "false";
    if (typeof v === "number") {
      if (!Number.isFinite(v)) throw new Error(`non-finite number in schema: ${v}`);
      return JSON.stringify(v);
    }
    if (typeof v === "string") {
      // JSON.stringify escapes quotes, backslashes and C0 controls as Python
      // does; with ensure_ascii=False neither escapes anything else.
      return JSON.stringify(v);
    }
    if (Array.isArray(v)) return `[${v.map(enc).join(",")}]`;
    if (typeof v === "object") {
      const keys = Object.keys(v).sort();
      return `{${keys.map((k) => `${enc(k)}:${enc(v[k])}`).join(",")}}`;
    }
    throw new Error(`unencodable value of type ${typeof v}`);
  };
  return enc(value);
}

async function generate() {
  let raw;
  try {
    raw = readFileSync(schemaPath, "utf-8");
  } catch (err) {
    throw new Error(`cannot read the committed schema at ${schemaPath}: ${err.message}`);
  }
  const schema = JSON.parse(raw);
  const sha = createHash("sha256").update(pythonCanonicalJson(schema), "utf-8").digest("hex");
  const ast = await openapiTS(schema, {
    alphabetize: false,
    exportType: false,
    // absent != null: optional fields stay optional, nullable ones stay `| null`
    defaultNonNullable: false,
  });
  const rel = relative(uiRoot, schemaPath).split("\\").join("/");
  const banner =
    "/**\n" +
    ` * GENERATED by ui/scripts/gen-api.mjs from ${rel} — DO NOT EDIT.\n` +
    " * Regenerate: `npm run gen:api`. Freshness: `npm run check:api`.\n" +
    " */\n\n";
  const types = banner + astToString(ast);
  const meta =
    banner +
    "/** sha256 of the canonical schema JSON this client was generated from;\n" +
    " *  compared with /info.api.schema_sha256 on connect. */\n" +
    `export const SCHEMA_SHA256 = "${sha}";\n` +
    "/** the API major version this client speaks (/info.api.version). */\n" +
    `export const API_VERSION = "${schema.info?.version?.split(".")[0] ?? "1"}";\n` +
    "/** the path prefix every generated route starts with. */\n" +
    'export const API_PREFIX = "/api/v1";\n';
  return { types, meta, sha };
}

function readOr(path) {
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return null;
  }
}

try {
  const { types, meta, sha } = await generate();
  if (check) {
    const stale = [];
    if (readOr(outTypes) !== types) stale.push(relative(uiRoot, outTypes));
    if (readOr(outMeta) !== meta) stale.push(relative(uiRoot, outMeta));
    if (stale.length) {
      console.error(
        `STALE: ${stale.join(", ")} no longer match ../pleroma/serve/api-schema.json.\n` +
          "Run `npm run gen:api` in ui/ and commit the result (then fix any type errors it surfaces).",
      );
      process.exit(1);
    }
    console.log(`api types are current (schema sha256 ${sha})`);
  } else {
    writeFileSync(outTypes, types);
    writeFileSync(outMeta, meta);
    console.log(
      `wrote ${relative(uiRoot, outTypes)} and ${relative(uiRoot, outMeta)} (schema sha256 ${sha})`,
    );
  }
} catch (err) {
  console.error(`gen-api failed: ${err instanceof Error ? err.message : String(err)}`);
  process.exit(2);
}
